name: dddsample
version: 0.0.1
author: Tomochika Hara <tomochikahara@gmail.com>
description: This project is DDD Sample Application on Dart.
dependencies:
  intl: 0.4.5+1
  logging: 0.4.5+1
dev_dependencies:
  unittest: any
